# Generated by Django 5.0.1 on 2024-11-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currTime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
